### ISSUE TITLE
Template via-lb boot locations

### ISSUE THREAD

**Issue by George217** [F5Networks/f5-azure-arm-templates#197] opened 2020-07-13 05:28 UTC
## Do you already have an issue opened with F5 support?
No

## Description
For upgrade purposes and not pave and nuke. While deploying the template that states it will create two boot locations, it ends up creating one boot location with two logical Disks HD1:78GB and HD2:128GB. Where the HD2 do not exist under VM property only HD1. So creating a slot(installing an image) under HD2,such as HD2.1, will end up with an error "disk do not exist"
But installing a boot location under HD1 such as HD1.2 is not throwing an error and the new image gets installed but the disk space for that slot HD1.2 is only 23GB which I think is not enough and will cause issues later while provisioning multiple modules.
Why the template is not creating two boot locations? Or is it an expected behavior as explained above.
## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol#installation

## Severity Level
3

**Comment by shyawnkarim** [comment] 2020-10-02 17:09
I deployed this template and was able to reproduce this issue. I have filed a bug for this, internal ID ESECLDTPLT-2260

The template does still deploy a disk big enough to hold two slots. Here is a link to a [support article](https://support.f5.com/csp/article/K17406) to help with this issue while we wait for this to be fixed.

**Comment by shyawnkarim** [comment] 2022-11-15 20:57
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

**Closed** 2022-11-15 20:57 UTC
Labels: bug, wontfix
