### ISSUE TITLE
Deployment template does not use IP addresses from selected subnet

### ISSUE THREAD

**Issue by andreasforseth** [F5Networks/f5-azure-arm-templates#128] opened 2019-05-24 12:21 UTC
## Do you already have an issue opened with F5 support?
No

## Description
We are trying to deploy a failover cluster to an existing stack with a template.

We have selected a subnet of 10.x.x.192/27 for the external self-ip and have before deployment configured the subnets in Azure. 
We have the following settings:
External Subnet Name: FWoutsideSubet
External IP Address Range Start: 10.x.x.196
External Ip Self Address Range Start: 10.x.x.200

When we deploy we get an error message for resource bigip-ext0 that say "Private static IP address **10.x.x.10** does not belong to the range of subnet prefix **10.x.x.192/27**."

It looks like it have predefined addresses in the script that want to use .10 for ext0 and .11 for ext1.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/blob/master/supported/failover/same-net/via-lb/3nic/existing-stack/byol/Deploy_via_PS.ps1

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by namhly** [comment] 2019-05-24 17:05
Hi Andreas,
Thank you for submitting this issue. We've created an internal issue, 1395, to track this bug. The fix will come out in the coming release. In mean time, please use the previous version for your deployment:

https://github.com/F5Networks/f5-azure-arm-templates/tree/v6.0.4.0/supported/failover/same-net/via-lb/3nic/existing-stack/byol

Thank you.

**Comment by andreasforseth** [comment] 2019-05-28 07:44
Hi @namhly,

will the fix be included in the release that are planned for around the 18/6? 

Best Regards
Andréas

**Comment by namhly** [comment] 2019-05-28 17:54
Hi Andreas,
Yes, it will be.

**Comment by gulycka** [comment] 2019-05-31 15:05
Hi guys,

I encountered the same issue.
Problem is that somebody forget to remove hardcoded values (.10 and .11) from template.
`"privateIPAddress": "[concat(variables('extSubnetPrivateAddressPrefix'), 10)]",
"privateIPAddress": "[concat(variables('extSubnetPrivateAddressPrefix'), 11)]",`

Values for requested IP addresses were stored in variables, but not used.
`"extSubnetPrivateAddressSuffix0": "[add(variables('extSubnetPrivateAddressSuffixInt'), 1)]", 
"extSubnetPrivateAddressSuffix1": "[add(variables('extSubnetPrivateAddressSuffixInt'), 2)]",`

I edited the template and used the statments used in previous version of template.
`"privateIPAddress": "[concat(variables('extSubnetPrivateAddressPrefix'), variables('extSubnetPrivateAddressSuffix0'))]",
"privateIPAddress": "[concat(variables('extSubnetPrivateAddressPrefix'), variables('extSubnetPrivateAddressSuffix1'))]",`

After this change, template was deployed successfully.

Also I noticed that if I request "External Ip Address Range Start" for example 10.1.1.100, I will get two Ip addresses - 10.1.1.101 and 10.1.1.102. I think first IP address should be the one, that is in External Ip Address Range Start. So I should get 10.1.1.100 and 10.1.1.101 instead.

To have it like this, you need to change these two variables from
`"extSubnetPrivateAddressSuffix0": "[add(variables('extSubnetPrivateAddressSuffixInt'), 1)]", 
"extSubnetPrivateAddressSuffix1": "[add(variables('extSubnetPrivateAddressSuffixInt'), 2)]",`
to
`"extSubnetPrivateAddressSuffix0": "[add(variables('extSubnetPrivateAddressSuffixInt'), 0)]",
"extSubnetPrivateAddressSuffix1": "[add(variables('extSubnetPrivateAddressSuffixInt'), 1)]",`

Btw how is it even possible that template in "Supported" section failed in deployment and there are some forgotten hardcoded numbers?
Is it even tested?

I am attaching the fixed and working version of template with resolved two bugs mentioned above.
[template.json.txt](https://github.com/F5Networks/f5-azure-arm-templates/files/3241788/template.json.txt)

Thanks,
gulycka.

**Comment by edwoodjrjr** [comment] 2019-05-31 15:25
Hi, the issue was caused by an error in our automated template generation process.  We run multiple daily tests, but the test case inputs just happened to mask the problem, so the tests passed.   We will investigate the +1 on the created IPs, thanks for mentioning it.

**Comment by jsevedge** [comment] 2019-07-01 16:39
This issue was resolved in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v7.0.0.0

Please feel free to reopen if you have further questions.

**Closed by jsevedge** 2019-07-01 16:39 UTC
Labels: bug
