### ISSUE TITLE
F5 Azure Deployment getting failed Intermittently with error "ssh host key: ret=255, out= /config/ssh/ssh_host_rsa_key.pub".

### ISSUE THREAD

**Issue by Sri-9339** [F5Networks/f5-azure-arm-templates#191] opened 2020-06-14 15:13 UTC
## Do you already have an issue opened with F5 support?
NO

## Description
F5 Azure Deployment getting failed Intermittently with below Error.

**ErrorCode:** The resource operation completed with terminal provisioning state 'Failed'

**Message:** SSH host key generation failed. Error details: Failed to generate ssh host key: ret=255, out= /config/ssh/ssh_host_rsa_key.pub is not a public key file.\\n. To resolve this issue verify if Linux agent is set up properly
![new-error1](https://user-images.githubusercontent.com/57702396/84597141-55b18b80-ae7f-11ea-9553-d8d5f55991cf.PNG)

## Template

Deploying the BIG-IP VE in Azure - 3 NIC
f5-azure-arm-templates/supported/standalone/3nic/existing-stack/byol/

## Severity Level

Severity: 3

**Comment by shyawnkarim** [comment] 2020-06-17 20:12
I've never seen anyone come across this issue before from using our templates.

It could be an OpenSSL issue. There are people discussing [OpenSSL issues on StackOverflow](https://stackoverflow.com/questions/29010967/openssl-unable-to-load-public-key). Maybe try taking a look there and recreating a key?

**Comment by 53d117460ec63d70** [comment] 2020-07-23 12:25
I am also seeing this issue with the [HA via-api template](https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg) using version ```15.1.002000``` with imageName ```Best1Gbps``` and instanceType ```Standard_DS3_v2```. [There is an F5 bugtracker for this issue](https://cdn.f5.com/product/bugtracker/ID807401.html) relating to version ```14.1.003000``` suggesting using specific instance types as a workaround. As I am already using one of the suggested instance types this must not be applicable to version ```15.1.002000```? If I ssh onto the VM I am able to verify the host key without error:
```
ssh-keygen -l -E md5 -f /var/ssh/ssh_host_rsa_key.pub
```

**Comment by shyawnkarim** [comment] 2020-10-15 14:52
The problem is that the Azure waagent tries to access the keys before they are generated. We are tracking this bug internally with VECLOUD-971.

**Comment by vvt137** [comment] 2020-11-03 02:04
I have observed the same issue using [Standalone 2nic PAYG](https://github.com/F5Networks/f5-azure-arm-templates/tree/v9.1.0.0/supported/standalone/2nic/existing-stack/payg) template with imageName `Best25Mbps`, BIG-IP version 15.1.0 and InstanceType `Standard_DS2_v2`. 

Importantly, changing the InstanceType to `Standard_D2_v2` fixed the problem. This somewhat contradicts the [Bug ID 807401](https://cdn.f5.com/product/bugtracker/ID807401.html) article which recommends using DS-type images as a workaround. Perhaps, `Standard_D3_v2` will also work instead of the failing `Standard_DS3_v2` implementation described [above](https://github.com/F5Networks/f5-azure-arm-templates/issues/191#issuecomment-662977255).

**Comment by shyawnkarim** [comment] 2022-11-15 21:06
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

**Closed** 2022-11-15 21:06 UTC
Labels: bug, known issue
