### ISSUE TITLE
Availability Zone Options in Template

### ISSUE THREAD

**Issue by kantkrish** [F5Networks/f5-azure-arm-templates#120] opened 2019-03-15 13:49 UTC
## Description
Can the option to select "Availability Zones" be added to the Template?

## Severity Level

Severity: 2

**Comment by edwoodjrjr** [comment] 2019-03-15 13:53
This is a duplicate of https://github.com/F5Networks/f5-azure-arm-templates/issues/74 (tracked with issue 993).

**Comment by edwoodjrjr** [comment] 2019-04-15 19:06
Closing as duplicate.

**Closed by edwoodjrjr** 2019-04-15 19:06 UTC
