### ISSUE TITLE
Microsoft.Compute/virtualMachines/extensions Conflict

### ISSUE THREAD

**Issue by erjuancho** [F5Networks/f5-azure-arm-templates#241] opened 2023-01-12 21:30 UTC
Hi all. Need your help to know why is this failing. When I deploy the PAYG template the extension installation fails with 
"**_Status Message: VM has reported a failure when processing extension 'start'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1
[stdout]

[stderr]
/bin/sh: -c: line 109: unexpected EOF while looking for matching `''
/bin/sh: -c: line 110: syntax error: unexpected end of file
"

More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot  (Code:VMExtensionProvisioningError)_**"

I´m running this version:
"f5CloudLibsTag": "v4.27.1",
"f5CloudLibsAzureTag": "v2.17.1",
"f5NetworksTag": "v10.2.0.0",

Many thanks!

**Comment by shyawnkarim** [comment] 2023-01-12 23:42
@erjuancho which PAYG template are you deploying?

**Comment by erjuancho** [comment] 2023-01-13 00:22
Thank you @shyawnkarim, Im trying to deploy 3nic - Existing Stack - Payg. And the latetst release (10.2.0.0)

https://github.com/F5Networks/f5-azure-arm-templates/blob/v10.2.0.0/supported/failover/same-net/via-lb/3nic/existing-stack/payg/azuredeploy.json

**Comment by shyawnkarim** [comment] 2023-01-13 21:27
I got the same error message when deploying today. This bug is now being tracked internally with ID, ESECLDTPLT-3248.

**Comment by erjuancho** [comment] 2023-01-16 16:52
Hi @shyawnkarim. Is there any ETA for this? we need to execute at least 4 deployments and this ARM template is critical. Otherwise we need to reevaluate schedules internally. 

Will be good to know the last working version. I tried with  tag version 9.5.0.0 using 

"f5CloudLibsTag": "v4.25.0",
"f5CloudLibsAzureTag": "v2.17.0",
"f5NetworksTag": "v9.5.0.0",

And the result was the same.

Regards!

**Comment by erjuancho** [comment] 2023-01-17 17:45
Hi @shyawnkarim, here is the param file.


`{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "10.2.0.0",
    "parameters": {
        "adminUsername": {
            "value": "Admin"
        },
        "authenticationType": {
            "value": "password"
        },
        "adminPasswordOrKey": {
            "value": ""
        },
        "dnsLabel": {
            "value": "vpn-000"
        },
        "instanceName": {
            "value": "F5VM"
        },
        "numberOfExternalIps": {
            "value": 1
        },
        "enableNetworkFailover": {
            "value": "Yes"
        },
        "provisionInternalLoadBalancer": {
            "value": "Yes"
        },
        "internalLoadBalancerProbePort": {
            "value": "3456"
        },
        "instanceType": {
            "value": "Standard_DS3_v2"
        },
        "imageName": {
            "value": "Best1Gbps"
        },
        "bigIpVersion": {
            "value": "15.1.501000"
        },
        "bigIpModules": {
            "value": "ltm:nominal, apm:nominal"
        },
        "vnetName": {
            "value": "Vnet"
        },
        "vnetResourceGroupName": {
            "value": "VnetRSG"
        },
        "mgmtSubnetName": {
            "value": "NETSBN05"
        },
        "mgmtIpAddressRangeStart": {
            "value": "DYNAMIC"
        },
        "externalSubnetName": {
            "value": "NETSBN03"
        },
        "externalIpAddressRangeStart": {
            "value": "DYNAMIC"
        },
        "externalIpSelfAddressRangeStart": {
            "value": "DYNAMIC"
        },
        "internalSubnetName": {
            "value": "NETSBN04"
        },
        "internalIpAddressRangeStart": {
            "value": "DYNAMIC"
        },
        "provisionPublicIP": {
            "value": "Yes"
        },
        "provisionPublicIPApp": {
            "value": "Yes"
        },
        "declarationUrl": {
            "value": "NOT_SPECIFIED"
        },
        "ntpServer": {
            "value": "0.pool.ntp.org"
        },
        "timeZone": {
            "value": "UTC"
        },
        "customImageUrn": {
            "value": "OPTIONAL"
        },
        "customImage": {
            "value": "OPTIONAL"
        },
        "restrictedSrcAddress": {
            "value": "10.0.0.69"
        },
        "tagValues": {
            "value": {
                "ROLE_PURPOSE": "P2S F5 VPN",
                "ENGAGEMENT_ID": "ID",
                "OWNER": "owner@mail.net",
                "DEPLOYMENT_ID": "NET",
                "PRODUCT_APP": "P2S",
                "ENVIRONMENT": "Production",
                "ROLE": "F5 P2S VPN"
            }
        },
        "allowUsageAnalytics": {
            "value": "Yes"
        },
        "allowPhoneHome": {
            "value": "Yes"
        }
    }
}`

**Comment by shyawnkarim** [comment] 2023-01-17 18:31
Engineering has looked into this we would like you try deploying again with some changes to your parameter file. Please let us know if this solves your issue.

"adminUsername": { "value": "Admin" }  --> "azureuser"
"instanceType": { "value": "Standard_DS3_v2" }  --> "Standard_D8s_v4" or larger. 
"bigIpModules": { "value": "ltm:nominal, apm:nominal" }. --> "ltm:nominal,apm:nominal"
"restrictedSrcAddress": { "value": "10.0.0.69" }  --> "10.0.0.69/32"

**Comment by erjuancho** [comment] 2023-01-18 15:43
Hi @shyawnkarim I tried using the param file you provide (the original) with no changes, and the result is the same. I don´t think the issue is a VM capacity. The error message point to some error in one scritpt.  The error message `/bin/sh: -c: line 109: unexpected EOF while looking for matching `''` looks like there is an extra (') somewhere in the script, but I can't find where. Extension has a lot of complexity and it will take me a lot of time to look at it.

Thanks!!

**Comment by shyawnkarim** [comment] 2023-01-25 19:37
I had our engineering team take a look at this issue and they were unable to reproduce the error you are seeing when those parameters were changed to the ones I suggested in my previous comment.

**Comment by shyawnkarim** [comment] 2023-01-25 22:42
Can you send all of the logs from these two places? 

1. /var/log/cloud/azure/*
2. /var/log/cloud/bigIpRuntimeInit.log

Please send your logs directly to me at s.karim@f5.com.

**Comment by erjuancho** [comment] 2023-02-15 19:34
Hi @shyawnkarim Sorry for my late response, I couldn't find time to work in this because I was in a hurry to deploy the F5's. Now that I have a little free time to work with the issue I was trying to reproduce the issue, and no matter what parameter file I use, the job is now working good. Even last week I deployed an stand alone appliance using the template you provide and the extension installation failed as well. Today I deploy that very same deployment and works without any issue. I don't know if you fix something from your side. But I think I can say that the issue is no longer an issue. Please let me know if you need somethin else from my side, otherwise I think we can close this now

Thanks for your help

**Comment by shyawnkarim** [comment] 2023-02-21 17:09
Closing.

Thats great to heat that it is working for you now. If you do run into the same issue again, please leave a comment here and I'll open it back up.

**Closed** 2023-02-21 17:10 UTC
Labels: bug
