### ISSUE TITLE
failover via LB - enableNetworkFailover to yes but devices are not fully configured

### ISSUE THREAD

**Issue by Klipope** [F5Networks/f5-azure-arm-templates#232] opened 2021-11-23 16:13 UTC
using the latest image uploaded in marketplace: 16.1.1.0000 
using template: https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/failover/same-net/via-lb/3nic/existing-stack/byol 
resources are deployed but the failover network configuration is incomplete on both devices. 
failover unicast configuration is empty 
if I manually configure the internal or external subnets in the configuration on both device then the cluster is up and running in Active/standby. 

most likely an issue due to the new 16.1.1? 
tried it 3 times and always with the same outcome. 
thanks

**Comment by shyawnkarim** [comment] 2021-12-02 20:24
Thanks for submitting this issue. I was able to duplicate the behavior with three different images:

- f5-networks:f5-big-ip-byol:f5-big-all-2slot-byol:15.1.400000

- f5-networks:f5-big-ip-byol:f5-big-all-2slot-byol:16.1.000000

- f5-networks:f5-big-ip-byol:f5-big-all-2slot-byol:16.1.100000

This issue is now being tracked internally with ID ESECLDTPLT-2918.

**Comment by Klipope** [comment] 2021-12-03 08:03
thanks @shyawnkarim !

**Comment by shyawnkarim** [comment] 2021-12-14 16:41
This template should work if an IP address is provided for the parameter internalIpAddressRangeStart instead of DYNAMIC. Please let me know if you are able to deploy with this change.

**Comment by Klipope** [comment] 2022-01-10 08:21
@shyawnkarim just tested today with the change you mentioned and no.. I end up in the same situation. Both devices are standalone. the "Failover Unicast Configuration" configuration is empty on both devices. I used the 9.7.0 template with version 16.1.0. only change I made was to provision APM on top of LTM + your change in the "internalIpAddressRangeStart" field.

**Comment by jmcalalang** [comment] 2022-01-21 17:05
Is there an update on when this will get resolved in the template? We have another customer who just ran into this.

**Comment by shyawnkarim** [comment] 2022-01-21 17:14
When engineering took a look at this issue they weren't able to reproduce the error when deploying with static IPs. @Klipope, can you send me your parameters file? s.karim@f5.com

**Comment by jmcalalang** [comment] 2022-01-21 17:17
deploying static isnt a fix, its a work around. is there going to be a fix to continue to use dynamic?

**Comment by mikeoleary** [comment] 2022-01-21 17:54
I have to agree, deploying with Static IP is not a fix, it's a workaround and most deployments I see will use the default value of dymanic, so this does affect us.

**Comment by shyawnkarim** [comment] 2022-01-21 17:55
I've opened a new bug, internal ID ESECLDTPLT-2939, to investigate why DYNAMIC is not working as intended.

**Comment by Klipope** [comment] 2022-01-21 19:15
sorry but even with static it did not work for me. @shyawnkarim will send you my parameters file.

**Comment by shyawnkarim** [comment] 2022-06-06 23:01
Closing.

This issue was resolved with [Release 9.8.0.0](https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v9.8.0.0).

**Closed** 2022-06-06 23:01 UTC
Labels: bug
