### ISSUE TITLE
BIG-IQ Templates where BIG-IQ uses External Auth (Active Directory/LDAP) fail to license the BIG-IP

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-azure-arm-templates#99] opened 2018-10-30 08:01 UTC
## Description
Describe the problem you're having or the enhancement you'd like to request.

BIG-IQ Templates where BIG-IQ uses External Auth (Active Directory/LDAP) fail to license the BIG-IP. from azure/cloud logs on the BIG-IP you see cloud libs become self aware of BIG-IP then you see the call out to IQ and it times out about 15 minutes later. I believe this is related to the fact you have to specify a provider in the rest call for login if you are using external auth, which there isnt called out in cloud libs. 

If this is called out someplace please let me know  :)

partner tester: @codygreen 

## Template
For bugs, enter the template with which you are experiencing issues below.

This was tested on the existing stack 3-nic standalone, from a few different deployments

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: **Severity 3 (Medium)**

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by namhly** [comment] 2018-11-21 23:08
Thanks Jon. We will look into this problem.
In mean time, can you please provide some details:
- What template did you use?
- How did you reproduce/test it?

Thanks,

**Comment by jsevedge** [comment] 2019-04-15 21:44
@jmcalalang I am making an assumption you meant BIG-IP templates fail?  In any case internal ID 1195 created to track this.

**Comment by shyawnkarim** [comment] 2022-11-12 00:07
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).

If this issue is still important to you, please file an issue in the V2 repo.

**Closed** 2022-11-12 00:07 UTC
Labels: bug, wontfix, id created
