### ISSUE TITLE
Unable to deploy Active/Standby HA cluster in Australia East region

### ISSUE THREAD

**Issue by chammidhan** [F5Networks/f5-azure-arm-templates#133] opened 2019-06-30 22:09 UTC
I'm getting the following error when I try to deploy the template for Active/Standby cluster in Australia East region. This region does not have availability zones.

failed validation with message: 'The resource type 'virtualMachines' does not support availability zones at location 'australiaeast' and api-version '2018-05-01'.'.'."}]}

**Comment by chammidhan** [comment] 2019-07-01 06:45
Managed to work around it by changing line 576 from

"zonesAvailable": "[contains(variables('zoneMappings'), concat('\"', variables('location'), '\"'))]",

to

"zonesAvailable": false,

I'm no JSON expert so this probably requires a better fix.

**Comment by andreykashcheev** [comment] 2019-07-01 17:57
@chammidhan 
Thanks for reporting this problem! 
We are looking at this issue....

**Comment by andreykashcheev** [comment] 2019-07-01 19:08
This issue has been triaged and confirmed; the issue is tracked internally with the following ticket: 1473
We will provide an update as soon as this issue will be fixed. 

Let us know if you have any questions/concerns

**Comment by chammidhan** [comment] 2019-07-08 02:54
@andreykashcheev 
Wondering whether this was fixed or not. I am facing a problem with fail over and I have a feeling it might have something to do with the change I made in the template.

**Comment by andreykashcheev** [comment] 2019-07-08 15:30
@chammidhan 
This issue was triaged and we created a bug/story to fix it in the upcoming sprint. The fix would be available with the next Release. 

Could you please provide more details about the issue which you are facing with failover scenario? We might would be able to advise on fix/workaround.

Also, I would like to point out that according to Azure docs, Availability Zones are not supported in Australian region:
https://docs.microsoft.com/en-us/azure/availability-zones/az-overview#services-support-by-region
and I am wondering if there is some other limitations on Azure side which impacts failover scenario

Let me know if you have any questions/concerns

**Comment by chammidhan** [comment] 2019-07-09 02:52
Hi Andrey,

Thanks for getting back to me. Yes I do understand that this region does
not support Availability Zones and we are fine with that.

The issue with the failover is that, from F5s perspective, the failover
happens successfully. But the secondary IPs of the external interface
(which are used as our virtual server IPs) always remain on the first
appliance regardless which one is active. So the traffic to virtual servers
always come to the first appliance. This is the IP configuration from
STANDBY appliance.
[image: image.png]





And this is from the ACTIVE appliance
[image: image.png]



Ideally, I should be seeing the secondary IPs on ext1 interface when the
second appliance is Active. But these IPs never move.
I was thinking whether the modification I did in the template might have
something to do with this part failing.

What's the ETA on the next release?

**Comment by edwoodjrjr** [comment] 2019-07-09 14:26
@chammidhan For the Availability Zones issue, we are applying zones based on the Azure compute provider's zoneMappings attribute.  As you can see, the provider is incorrectly listing australiaeast as supporting this:

[{"location":"eastus2","zones":["1","2","3"]},{"location":"centralus","zones":["1","2","3"]},{"location":"westeurope","zones":["1","2","3"]},{"location":"eastus2euap","zones":["1","2","3"]},{"location":"centraluseuap","zones":["1","2"]},{"location":"francecentral","zones":["1","2","3"]},{"location":"southeastasia","zones":["1","2","3"]},{"location":"westus2","zones":["1","2","3"]},{"location":"northeurope","zones":["1","2","3"]},{"location":"eastus","zones":["1","2","3"]},{"location":"uksouth","zones":["1","2","3"]},{"location":"japaneast","zones":["1","2","3"]},**{"location":"australiaeast","zones":["1","2","3"]}**]

We've opened Azure support case #119070824002212 for this issue.

Regarding the failover errors, can you post the sanitized output of /var/log/cloud/azure/failover.log from the device that became active? You can also open a case with F5 support; they will escalate to the appropriate folks.

**Comment by chammidhan** [comment] 2019-07-09 23:07
Hi Mike,

Thanks for the info. I already have an F5 support case for this.
C3037298
Attached the failover log.

**Comment by edwoodjrjr** [comment] 2019-07-10 14:31
@chammidhan I will keep an eye on the case.  One question...do you have virtual addresses configured in traffic groups on the BIG-IP that match the private IP addresses of Azure IP configurations?

**Comment by chammidhan** [comment] 2019-07-11 00:06
Hi Mike,

I'm not clear on the question. The virtual IPs are on the subnet which is
allocated for the External Interface of the F5 as shown in the screenshot I
sent previously. Does that answer your question?

**Comment by shyawnkarim** [comment] 2019-12-20 18:44
Our templates have been updated so that template validation succeeds without any issues in the affected availability zones.

**Comment by chammidhan** [comment] 2019-12-20 21:04
Thanks Shyawn!

**Comment by shyawnkarim** [comment] 2020-06-09 17:43
Closing. This issue was resolved with Release 7.1.0.0.

**Closed by shyawnkarim** 2020-06-09 17:43 UTC
Labels: bug
