### ISSUE TITLE
per app VE using failover via API doesn't deploy network, fails HA setup

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#114] opened 2019-02-14 05:40 UTC
## Description
Azure failover same-net via API with BIG-IQ deploys 2 F5s in standalone only instead of proper HA setup. When I view cloud logs, nothing really stands out in the failover or cluster log...just looks like things didn't finish. When I check BIG-IP configs, there are no self IPs. 

network.log looks clean, no errors.
Also, Greg asked me to check cloud-libs-err.log but I don't see that file anywhere.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/new-stack/bigiq

**Comment by JeffGiroux** [comment] 2019-02-14 05:45
I also tested various workarounds today:

1. using standard DS5_v2 instance works
2. using version 12.1.3 works
3. using version 13.1.1 does NOT work
4. using standard DS3_v2 instance does NOT work
5. using regular multi-app VE (aka Best licensing) works

I need v13.1.1 working with per app on the failover via API. I'm glad 12.1.3 works, but I need 13.1.1.

**Comment by edwoodjrjr** [comment] 2019-02-14 14:55
This looks like a duplicate of https://github.com/F5Networks/f5-azure-arm-templates/issues/112

**Comment by edwoodjrjr** [comment] 2019-04-11 21:36
This was fixed in v6.0.4.0.  Please reopen issue #112 if this is still a problem.

**Closed by edwoodjrjr** 2019-04-11 21:36 UTC
